intranet/portal/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import (TextAreaField,
                     StringField,
                     SubmitField,
                     HiddenField,
                     BooleanField,
                     DecimalField,
                     DateField,
                     TimeField,
                     FormField,
                     FieldList,
                     IntegerField,
                     RadioField,
                     PasswordField,
                     SelectField,
                     FloatField,
                     FileField,
                     EmailField)

from wtforms.validators import (InputRequired,
                                DataRequired,
                                NumberRange,
                                Email,
                                EqualTo,
                                Optional)

class LoginForm(FlaskForm):
    email = StringField('Email Address')
    password = PasswordField('Password')
    login = SubmitField('Login')

intranet/portal/__init__.py
from flask import Blueprint

portal = Blueprint('portal', __name__, template_folder='templates')

intranet/portal/views.py
from flask import flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user

from . import portal
from .forms import LoginForm
from intranet.user import CustomerUser


@portal.route('/login_old', methods=['GET', 'POST'])
def login_old():
    # Here we use a class of some kind to represent and validate our
    # client-side form data. For example, WTForms is a library that will
    # handle this for us, and we use a custom LoginForm to validate.
    form = LoginForm()
    if form.validate_on_submit():
        # Login and validate the user.
        # user should be an instance of your `User` class
        user = CustomerUser.get_by_email(form.email.data)
        if user and user.check_pwd(form.password.data):
            login_user(user)

            flash('Logged in successfully.')

            next = request.args.get('next')

            return redirect(next or url_for('portal.home'))
        else:
            flash('Login Failed', 'error')
            
    return render_template('portal/login.html', form=form)

@portal.route('/')
@login_required
def home():
    return render_template('portal/home.html')

@portal.route('/bookings')
@login_required
def show_bookings():
    return render_template('portal/bookings.html')

@portal.route('/pets')
@login_required
def show_pets():
    return render_template('portal/pets.html')

@portal.route('/profile')
@login_required
def show_profile():
    return render_template('portal/profile.html')

@portal.route('/forgot_password')
def forgot_password():
    return render_template('portal/forgot_password.html')

@portal.route('/register')
def register():
    return render_template('portal/register.html')

intranet/views/portal.py
from flask import flash, render_template, request, jsonify
from flask_login import current_user

from intranet import portal
from utils import db, parse_date

@portal.route('/')
def home():
    return render_template('portal/home.html')

@portal.route('/bookings')
def show_bookings():
    return 'My Bookings'

@portal.route('/pets')
def show_pets():
    return 'My Pets'

@portal.route('/profile')
def show_profile():
    return 'My Profile'

@portal.route('/password')
def change_password():
    return 'Change Password'

@portal.route('/login')
def login():
    return render_template('portal/login.html')

@portal.route('/logout')
def logout():
    return 'Logout'

intranet/templates/portal/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <script src="https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.noStyle.js"></script>
    {% include 'components/css.html' %}
    {% block head %} {% endblock head %}

    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }}
    </script>
    <title>{% block title %}{% endblock title %}</title>
    
    </head>
    <body class="mx-auto">
      <header class="fixed-top noprint">
        <div class="navbar navbar-dark bd-navbar" id="topheader">
          <nav class="container-xl flex-wrap flex-md-nowrap" aria-label="Main Navigation">
            <a class="navbar-brand ms-3" href="/"><img src="/static/img/logo.jpg" width="40" height="40" alt=""></a>
              <ul class="navbar-nav flex-row gap-3 bd-navbar-nav pt-2 py-my-0">
                <a class="nav-link" href="{{ url_for('portal.show_bookings') }}" id="navbarRequestDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Bookings
               </a>
               <a class="nav-link" href="{{ url_for('portal.show_pets') }}" id="navbarRequestDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Pets
                </a>
                <a class="nav-link" href="{{ url_for('portal.show_profile') }}" id="navbarRequestDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profile
                </a>
                  {% if current_user.is_authenticated %}
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ current_user.username }}
                      </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li>
                        <a class="dropdown-item" href="{{ url_for('portal.change_password') }}">Change Password</a>
                      </li>
                      <li>
                        <a class="dropdown-item" href="{{ url_for('portal.logout') }}">Logout</a>
                      </li>
                    </ul>
                  </li>
                  {% else %}
                    <li class="nav-item col-6 col-md-auto">
                      <a class="nav-link" href="{{ url_for('portal.login') }}">Login</a>
                    </li>
                  {% endif %}
            </ul>
        </nav>
        </div>
        <div id="status-bar" class="noprint d-flex justify-content-between align-items-stretch w-100">
          <div class="d-flex flex-grow-1">
              <div class="message-control" id="step-backward"><i class="fas fa-step-backward mx-auto"></i></div>
            <div id="status" class="flex-grow-1"></div>
            <div class="message-control" id="step-forward"><i class="fas fa-step-forward"></i></div>
          </div>
        </div>  
      </header>
        <div class="noprint" style="padding-top: 150px;">
      </div>

    <div class="modal fade" id="image-modal" tabindex="-1" role="dialog" aria-labelledby="imageModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" aria-label="Close" id="close-image-modal">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img id="fullSizeImage" src="" alt="Full Size Image" class="img-fluid">
          </div>
        </div>
      </div>
    </div>
    
  
<div id="content">
  {% block body %}
  {% endblock body %}
</div>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" integrity="sha512-T/tUfKSV1bihCnd+MxKD0Hm1uBBroVYBOYSk1knyvQ9VyZJpc/ALb4P0r6ubwVPSGB2GvjeoMAJJImBG12TiaQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js" integrity="sha512-zP5W8791v1A6FToy+viyoyUUyjCzx+4K8XZCKzW28AnCoepPNIXecxh9mvGuy3Rt78OzEsU+VCvcObwAMvBAww==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js" integrity="sha512-WHnaxy6FscGMvbIB5EgmjW71v5BCQyz5kQTcZ5iMxann3HczLlBHH5PQk7030XmmK5siar66qzY+EJxKHZTPEQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js" integrity="sha512-0bEtK0USNd96MnO4XhH8jhv3nyRF0eK87pJke6pkYf3cM0uDIhNJy9ltuzqgypoIFXw3JSuiy04tVk4AjpZdZw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <script src="/static/external/js/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.min.js" integrity="sha512-mh+AjlD3nxImTUGisMpHXW03gE6F4WdQyvuFRkjecwuWLwD2yCijw4tKA3NsEFpA1C3neiKhGXPSIGSfCYPMlQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <script src="https://kit.fontawesome.com/da7d0714e4.js" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://js.stripe.com/terminal/v1/"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/luxon/2.3.1/luxon.min.js" integrity="sha512-Nw0Abk+Ywwk5FzYTxtB70/xJRiCI0S2ORbXI3VBlFpKJ44LM6cW2WxIIolyKEOxOuMI90GIfXdlZRJepu7cczA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/luxon/2.3.1/luxon.min.js" integrity="sha512-Nw0Abk+Ywwk5FzYTxtB70/xJRiCI0S2ORbXI3VBlFpKJ44LM6cW2WxIIolyKEOxOuMI90GIfXdlZRJepu7cczA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <script src="/static/crowbank.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="/static/external/js/jquery.multiselect.js"></script>
    <script type="text/javascript" src="/static/external/js/webcam.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/htmx.org@1.9.4" integrity="sha384-zUfuhFKKZCbHTY6aRR46gxiqszMk5tcHjsVFxnUo8VMus4kHGVdIYVbOYYNlKmHV" crossorigin="anonymous"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
    <script src="/static/crowbank.js"></script>
    
    <script>
    {% with messages = get_flashed_messages(with_categories=true, category_filter=('error', 'warning', 'info')) %}
    {% if messages %}
      {% for (cat, msg) in messages %}
        $(() => { update_status('{{ cat }}', '{{ msg|safe }}')})
      {% endfor %}
    {% endif %}
  {% endwith %}  

  </script>
  </body>

    {% block scripts %}
    {% endblock scripts %}
</html>

intranet/templates/portal/home.html
<!DOCTYPE html>
<html lang="en">
    <body>
        <h1>Customer Portal</h1>
    </body>
</html>